### ISSUE TITLE
On composition and delegates - Question

### ISSUE THREAD

**Issue by Its-Kenta** [avwie/kotlin-blog#1]
Hello!
Sorry for actually creating an issue as I thought this would be best way to contact you.

I’ve been really enjoying reading your blog about composition by delegates and I’ve been trying to learn using it in game development.

my question actually is similar to the example “Dynamics” which I could translate to an Update function for entities. Now let’s say you have different types of entities who also operate on a different Update function where they require different parameters e.g. an Enemy needs a reference to Player to follow them or something alongside those words.

In this case, our update function is broken and now requires a different implementation for different entity? Or is that the idea behind Composition by Delegates?

Is there somewhat a way to actually utilise Observables with this system as well?

Sorry if I’m not making sense here! If something makes no sense please let me know and I will try to fix it up.

thank you for your hard work!

**Comment by avwie** [comment]
Hey, no worries! This is a good way of contacting me.

So if I understand you correctly you want to create an interface called update, like this:

```kotlin
interface Update {
  fun update()
}
```

However, the `update` function is actually dependent on the entity implementing the update? So, for an `Enemy` entity it would require an argument of `Player`?

If that is the case then you're correct, the update function requires a different implementation for every different entity. However, I think you need to rethink then what you'd use composition for. Composition is a way of adding behavior to 'something' by composing it of different smaller 'behaviors'. These smaller blocks of behaviors are pretty specific, but also general for all diffrent entities using them. Like, a health 'behavior' is pretty specific about health but general enough for all entities to use it. And since it is general we can implement it with a delegate. A class which has an implementation for this behavior that is sufficient enough for almost all use cases and so other entities can just delegate to this delegation class. If some sort of special use case is needed, an entity can always implement `Health` on its own.

So what is an 'update' behavior? What does it update? Its position? Or its health? Its weapons? Something else? Since it is quite vague what it should mean it also automatically becomes something that is difficult to implement with a typical delegation class. There is no way to pass additional arguments to this `update` function, since it is defined at the interface.

My assumption is you want something like an ECS? You iterate over all entities and you run the update on every one of them? But the implementation details of the update might vary?

So _a_ solution might be to have the different classes implement `Update` themselves. So no delegation. So how would you get a reference to the player then? Well... I suppose in the constructor?

```kotlin
class Orc(val player: Player, healthImpl: Health, spriteImpl: Sprite, dynamicsImpl: Dynamics, dangerousImpl: Dangerous):
    Update, Drawable, Health by healthImpl, Sprite by spriteImpl, Dynamics by dynamicsImpl, Dangerous by dangerousImpl {

   override fun update() {
      // do something with dynamics and player
      this.applyForce(....) // part of Dynamics
   }

    companion object {
        val sprite = SpriteImpl(ByteArray(0)) // just for mocking purposes

        fun new(player: Player, position: Pair<Double, Double>, damage: Int): Orc {
            return Orc(player, HealthImpl(150), sprite, DynamicsImpl(120.0, position), DangerousImpl(damage))
        }
    }
}
```

**Comment by Its-Kenta** [comment]
Thank you! This makes perfect sense now. I really appreciate you getting back to me on this one. 
Now that of course every entity would need to override the update func in the constructor, is this possible to do in the Builder Pattern you described? Or is it better to simply use the class's `new` func to create the instances?

**Comment by avwie** [comment]
I wouldn't recommend the builder pattern, that is just some syntactic sugar to be honest. Keep it simple with a constructor :)

**Comment by Its-Kenta** [comment]
Thank you.
I start to see what you mean by ` Composition is a way of adding behavior to 'something' by composing it of different smaller 'behaviors'.` as well.

It might take some time for me to fully grasp the idea behind it, but overall I much prefer to build components this way than being forever battling myself with inheritance and ECS itself is slightly too mind boggling to me (and tad too verbose, but everyone has their opinions on stuff like this).

I find Composition by Delegation to be the perfect sweet spot for me, and I'm certainly going to nurture the skill of it. So thank you so much for creating your blog post about this topic! It truly helped me a lot and I continue to read your blog as more post appear. I'm fairly new'ish to programming (and kotlin) so this is really helpful.

I will close the issue.
